// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDknOgf8Qg8kzNb4Ps69t7r7XwCd6Bx2_E',
    appId: '1:250277162942:web:23b4b5b4347c6ec7b613ef',
    messagingSenderId: '250277162942',
    projectId: 'zambiconnect',
    authDomain: 'zambiconnect.firebaseapp.com',
    storageBucket: 'zambiconnect.firebasestorage.app',
    measurementId: 'G-JPYP4NKHJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrcyMbi2Ymm24F92N8X0u-QVnwX4gEZZw',
    appId: '1:250277162942:android:e0d4b85bed27cbf4b613ef',
    messagingSenderId: '250277162942',
    projectId: 'zambiconnect',
    storageBucket: 'zambiconnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-1YlkHnHVqreB-y-lsIPuMRvZE4UFK1k',
    appId: '1:250277162942:ios:013cc51a68cdac3fb613ef',
    messagingSenderId: '250277162942',
    projectId: 'zambiconnect',
    storageBucket: 'zambiconnect.firebasestorage.app',
    iosBundleId: 'com.example.zamconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-1YlkHnHVqreB-y-lsIPuMRvZE4UFK1k',
    appId: '1:250277162942:ios:013cc51a68cdac3fb613ef',
    messagingSenderId: '250277162942',
    projectId: 'zambiconnect',
    storageBucket: 'zambiconnect.firebasestorage.app',
    iosBundleId: 'com.example.zamconnect',
  );
}
